# a config for bi-parametric sweep
# in parameters s and alpha
# "defaultSystem" describes default parameter values
# for studied system; system is always created with
# these parameters first
defaultSystem:
  w: 0
  a: -2.515
  b: -1.612684228842761
  r: 1
  param_to_index:
    w: 0
    a: 1
    b: 2
    r: 3
# grid describes parameter sweeps
# it must have either "first" AND "second" keys (biparametric),
# or "first" only (single parameter)
# each of these dictionaries must have following keys:
# "min": minimal parameter value
# "max":  maximal parameter value
# "steps": how many nodes between [min, max] including endpoints
# "caption": LaTeX version of parameter name, used for plotting
grid:
  first:
    left_n: 500
    right_n: 200
    left_step: 0.0005
    right_step: 0.0005
    name: a
    caption: \alpha
  second:
    down_n: 400
    up_n: 60
    down_step: 0.0005
    up_step: 0.0005
    name: b
    caption: \beta
# name of the task to perform
task: kneadings
# next entry must have the same name as value for "task" key
# stores parameters for performing task function, depends on what
# task function needs
sf_grid:
  start_eq: [0., 2.21648268, 4.47347482]
  input_data:
kneadings:
  dt: 0.01
  n: 50000
  stride: 1
  kneadings_start: 0
  kneadings_end: 7
  input_data:
route:
  start_pt:
  end_pt:
  only_map_flag: 0
# information for saving files
# "directory": where save it
# "mask": what is the prefix
# "useTimeStamp": "folder" or "file",
# - "ignore": ignores timestamp and uses "directory" and "mask" as is
# - "file": appends timestamp after "mask" for each saved file
# - "folder": creates folder with timestamp name and saves everything there
# "imageExtension": used specifically for images
output:
  directory: "./output/"
  mask: bigger_2
  useTimestamp: ignore
  imageExtension: png
# some functions might use additional keyword-arguments
# we can pass them through "misc" dictionary
misc:
  plot_settings:
    default:
      lines.linewidth: 6
      lines.color: black
      lines.markersize: 16
#      font.size: 26          # the default font size for text, given in points.
      xtick.labelsize: 20    # font size of the x tick labels
      ytick.labelsize: 20    # font size of the y tick labels
      axes.titlesize: 26     # font size of the axes title
      axes.labelsize: 26     # font size of the x and y labels
#      figure.titlesize: 20   # size of the figure title (``Figure.suptitle()``)
#      figure.labelsize: 20   # size of the figure label (``Figure.sup[x|y]label()``)
      figure.dpi: 100
      savefig.dpi: 300
  views:
    view_1:
      elev: 60
      azim: 160
      roll: 0
      xlim_left: 0
      xlim_right: 3
      ylim_left: 1.5
      ylim_right: 4.5
      zlim_left: 0
      zlim_right: 6.14
    view_2:
      elev: 0
      azim: 90
      roll: 0
      xlim_left: 0.5
      xlim_right: 2.25
      ylim_left: 1.5
      ylim_right: 4.5
      zlim_left: 3.5
      zlim_right: 5